name: PikaOS Kernel Build Only

on:
  workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/pikaos-linux/pikaos-builder:canary
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v3

    - name: Build Kernel
      run: ./main.sh
      
    - uses: actions/upload-artifact@v3
      with:
        name: PikaOS Kernel
        path: output/
