
name: PikaOS Kernel Build Only

on:
  workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ghcr.io/pikaos-linux/pika-kernel-container:sha256:f48d8d6ea24049351f74133da4232634c3bcb2ffe66e0ff7e6f2692fdd33d25d
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v3

    - name: Build Kernel
      run: ./main.sh
      
    - uses: actions/upload-artifact@v3
      with:
        name: PikaOS Kernel
        path: output/
